# Generated by Django 3.1.6 on 2021-02-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_file_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hoot_text',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
