# Generated by Django 3.1.6 on 2021-02-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210205_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hoot_text',
            new_name='hook_text',
        ),
    ]
